version: 2.1

parameters:
  min-rust-version:
    type: string
    default: "1.60"

executors:
  ubuntu:
    docker:
      - image: cimg/base

commands:
  make-test:
    parameters:
      rust-min-version:
        default: "1.56"
        type: string
    steps:
      - run:
          name: make test for minimium version <<parameters.rust-min-version>>
          command: |
            RUST_MIN_VERSION=<<parameters.rust-min-version>> make test
  
  make-publish:
    parameters:
      rust-min-version:
        default: "1.56"
        type: string
    steps:
      - run:
          name: Publish for minimium version <<parameters.rust-min-version>>
          command: |
            RUST_MIN_VERSION=<<parameters.rust-min-version>> make publish-tag

jobs:
  test:
    parameters:
      min-rust-version:
        type: string
    executor: ubuntu
    steps:
      - checkout
      - make-test:
          rust-min-version: << parameters.min-rust-version >>
  
  publish:
    parameters:
      min-rust-version:
        type: string
    executor: ubuntu
    steps:
      - checkout
      - make-publish:
          rust-min-version: << parameters.min-rust-version >>

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-only:
    jobs:
      - test:
          filters:
            branches:
              ignore: main
          matrix:
            parameters:
              min-rust-version:
                [
                  "1.56",
                  "1.60",
                ]
    
  test-publish:
    jobs:
      - test:
          filters: &filters-publish
            branches:
              only: main
          matrix:
            parameters:
              min-rust-version:
                [
                  "1.50",
                  "1.60",
                ]
      - publish:
          requires:
            - test
          filters:
           <<: *filters-publish
          matrix:
            parameters:
              min-rust-version:
                [
                  "1.50",
                  "1.60",
                ]
    