version: 2.1

parameters:
  min-rust-version:
    type: string
    default: "1.85"
  fingerprint:
    type: string
    default: SHA256:OkxsH8Z6Iim6WDJBaII9eTT9aaO1f3eDc6IpsgYYPVg
  validation-flag:
    type: boolean
    default: false
    description: "If true, the validation pipeline will be executed."
  success-flag:
    type: boolean
    default: false
    description: "If true, the success pipeline will be executed."
  release-flag:
    type: boolean
    default: false
    description: "If true, the release pipeline will be executed."

orbs:
  toolkit: jerus-org/circleci-toolkit@2.12.1
  sonarcloud: sonarsource/sonarcloud@3.0.0

filters: &filters
  tags:
    only: /.*/

executors:
  ubuntu:
    docker:
      - image: cimg/base:2025.07
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
  rust-env:
    docker:
      - image: jerusdp/ci-rust:<<pipeline.parameters.min-rust-version>>
  base_env:
    docker:
      - image: jerusdp/ci-rust:base

commands:
  make-test:
    parameters:
      rust-min-version:
        default: "1.56"
        type: string
    steps:
      - run:
          name: make test for minimum version <<parameters.rust-min-version>>
          command: |
            if [[ "1.85" == *"<<parameters.rust-min-version>>"* ]]; then
              wasi_name="wasm32-wasip1"
            else
              wasi_name="wasm32-wasi"
            fi

            REPO=jerusdp/ci-rust
            TAG=<<parameters.rust-min-version>>
            docker build \
                --build-arg MIN_RUST_VERSION=<<parameters.rust-min-version>> \
                --build-arg MIN_RUST_WASI=$wasi_name \
                -t ${REPO}/test:${TAG}-wasi \
                --target test .
            docker run --rm ${REPO}/test:${TAG}-wasi

  publish_rust_envs:
    parameters:
      rust-min-version:
        default: "1.56"
        type: string
    steps:
      - run:
          name: Publish for minimum version <<parameters.rust-min-version>>
          command: |
            if [[ "1.85" == *"<<parameters.rust-min-version>>"* ]]; then
              wasi_name="wasm32-wasip1"
            else
              wasi_name="wasm32-wasi"
            fi

            REPO=jerusdp/ci-rust
            TAG=<<parameters.rust-min-version>>
            INPUT_RELEASE_VERSION=0.1.0
            docker build \
                --build-arg MIN_RUST_VERSION=<<parameters.rust-min-version>> \
                --build-arg MIN_RUST_WASI=$wasi_name \
                -t ${REPO}:${TAG} \
                --target final .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push ${REPO}:${TAG}
      - run:
          name: Publish for minimum version <<parameters.rust-min-version>>
          command: |
            if [[ "1.85" == *"<<parameters.rust-min-version>>"* ]]; then
              wasi_name="wasm32-wasip1"
            else
              wasi_name="wasm32-wasi"
            fi

            REPO=jerusdp/ci-rust
            TAG=<<parameters.rust-min-version>>
            INPUT_RELEASE_VERSION=0.1.0
            docker build \
                --build-arg MIN_RUST_VERSION=<<parameters.rust-min-version>>\
                --build-arg MIN_RUST_WASI=$wasi_name \
                -t ${REPO}:${TAG}-wasi \
                --target wasi .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push ${REPO}:${TAG}-wasi

  publish_base_cmd:
    steps:
      - run:
          name: Publish for minimum version base
          command: |
            REPO=jerusdp/ci-rust
            INPUT_RELEASE_VERSION=0.1.0
            docker build -t ${REPO}:base --target final .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push ${REPO}:base

  cargo_audit:
    parameters:
      ignore_advisories:
        type: string
        default: ""
        description: "Additional parameters to list advisories that should be ignored"
    steps:
      - run:
          name: Security audit against RUSTSEC
          command: |
            cargo audit -D warnings << parameters.ignore_advisories >>

jobs:
  test:
    parameters:
      min-rust-version:
        type: string
    executor: ubuntu
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - make-test:
          rust-min-version: << parameters.min-rust-version >>

  publish_rustc_versions:
    parameters:
      min-rust-version:
        type: string
    executor: ubuntu
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - publish_rust_envs:
          rust-min-version: << parameters.min-rust-version >>

  publish_base:
    executor: ubuntu
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - publish_base_cmd

  security:
    executor:
      name: base_env
    parameters:
      ignore_advisories:
        default: ""
        description: List of advisories to ignore each prefixed with "--ignore "
        type: string
      cargo_audit:
        default: true
        description: Don't run the cargo audit scan
        type: boolean
      sonarcloud:
        default: true
        description: Don't run the sonarcloud scan
        type: boolean
    steps:
      - checkout
      - when:
          condition: << parameters.cargo_audit >>
          steps:
            - cargo_audit:
                ignore_advisories: << parameters.ignore_advisories >>
      - when:
          condition: << parameters.sonarcloud >>
          steps:
            - sonarcloud/scan
workflows:
  check_last_commit:
    when:
      and:
        - not:
            equal: [scheduled_pipeline, << pipeline.trigger_source >>]
        - not: << pipeline.parameters.success-flag >>
        - not: << pipeline.parameters.release-flag >>
        - not: << pipeline.parameters.validation-flag >>

    jobs:
      - toolkit/choose_pipeline:
          filters:
            branches:
              ignore: main
          name: choose pipeline based on committer
          context: bot-check

  validation:
    when:
      and:
        - not:
            equal: [scheduled_pipeline, << pipeline.trigger_source >>]
        - not: << pipeline.parameters.success-flag >>
        - not: << pipeline.parameters.release-flag >>
        - << pipeline.parameters.validation-flag >>
    jobs:
      - toolkit/label:
          min_rust_version: << pipeline.parameters.min-rust-version >>
          context: pcu-app
          filters:
            branches:
              only:
                - main
      - test:
          filters:
            branches:
              ignore: main
          matrix: &matrix
            parameters:
              min-rust-version:
                ["1.75", "1.76", "1.78", "1.79", "1.81", "1.82", "1.85"]
      - security:
          cargo_audit: false
          context:
            - SonarCloud
      - toolkit/update_changelog:
          requires:
            - test
            - security
          context:
            - release
            - bot-check
          ssh_fingerprint: << pipeline.parameters.fingerprint >>
          min_rust_version: << pipeline.parameters.min-rust-version >>

  on_success:
    when:
      and:
        - not:
            equal: [scheduled_pipeline, << pipeline.trigger_source >>]
        - << pipeline.parameters.success-flag >>
        - not: << pipeline.parameters.validation-flag >>

    jobs:
      - toolkit/end_success

  check_rebase:
    when:
      and:
        - not:
            equal: [scheduled_pipeline, << pipeline.trigger_source >>]
        - not: << pipeline.parameters.release-flag >>
    jobs:
      - toolkit/label:
          filters:
            branches:
              only: main
          min_rust_version: << pipeline.parameters.min-rust-version >>
          context:
            - bot-check

  release:
    when:
      and:
        - or:
            - and:
                - equal: [scheduled_pipeline, << pipeline.trigger_source >>]
                - equal: ["release check", << pipeline.schedule.name >>]
            - << pipeline.parameters.release-flag >>
        - not: << pipeline.parameters.success-flag >>
        - not: << pipeline.parameters.validation-flag >>
    jobs:
      - toolkit/make_release:
          context:
            - release
            - bot-check
          ssh_fingerprint: << pipeline.parameters.fingerprint >>
          min_rust_version: << pipeline.parameters.min-rust-version >>
          when_cargo_release: false
          when_use_workspace: false
          pcu_update_changelog: true

  deploy:
    when:
      not:
        equal: ["", << pipeline.git.tag >>]
    jobs:
      - publish_base:
          filters: *filters
      - publish_rustc_versions:
          matrix:
            <<: *matrix
          requires:
            - publish_base
          filters: *filters
