version: 2.1

parameters:
  min-rust-version:
    type: string
    default: "1.60"

executors:
  ubuntu:
    docker:
      - image: cimg/base:2024.01
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

commands:
  make-test:
    parameters:
      rust-min-version:
        default: "1.56"
        type: string
    steps:
      - run:
          name: make test for minimum version <<parameters.rust-min-version>>
          command: |
            REPO=jerusdp/ci-rust
            TAG=<<parameters.rust-min-version>>
            docker build --build-arg MIN_RUST_VERSION=<<parameters.rust-min-version>> -t ${REPO}/test:${TAG} --target test .
            docker run --rm ${REPO}/test:${TAG}

  make-publish:
    parameters:
      rust-min-version:
        default: "1.56"
        type: string
    steps:
      - run:
          name: Publish for minimum version <<parameters.rust-min-version>>
          command: |
            REPO=jerusdp/ci-rust
            TAG=<<parameters.rust-min-version>>
            INPUT_RELEASE_VERSION=0.1.0
            docker build --build-arg MIN_RUST_VERSION=<<parameters.rust-min-version>> -t ${REPO}:${TAG} --target final .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push ${REPO}:${TAG}

jobs:
  test:
    parameters:
      min-rust-version:
        type: string
    executor: ubuntu
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: default
      - make-test:
          rust-min-version: << parameters.min-rust-version >>

  publish:
    parameters:
      min-rust-version:
        type: string
    executor: ubuntu
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - make-publish:
          rust-min-version: << parameters.min-rust-version >>

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-only:
    jobs:
      - test:
          filters:
            branches:
              ignore: main
          matrix: &matrix
            parameters:
              min-rust-version: ["1.61", "1.65", "1.71", "1.72", "1.73", "1.74", "1.75"]

  test-publish:
    jobs:
      - test:
          filters: &filters-publish
            branches:
              only: main
          matrix:
            <<: *matrix
      - publish:
          requires:
            - test
          filters:
            <<: *filters-publish
          matrix:
            <<: *matrix
