version: 2.1

parameters:
  min-rust-version:
    type: string
    default: "1.60"
  fingerprint:
    type: string
    default: SHA256:OkxsH8Z6Iim6WDJBaII9eTT9aaO1f3eDc6IpsgYYPVg
  validation-flag:
    type: boolean
    default: false
    description: "If true, the validation pipeline will be executed."
  success-flag:
    type: boolean
    default: false
    description: "If true, the success pipeline will be executed."

orbs:
  toolkit: jerus-org/circleci-toolkit@0.23.0

executors:
  ubuntu:
    docker:
      - image: cimg/base:2024.07
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

commands:
  make-test:
    parameters:
      rust-min-version:
        default: "1.56"
        type: string
    steps:
      - run:
          name: make test for minimum version <<parameters.rust-min-version>>
          command: |
            REPO=jerusdp/ci-rust
            TAG=<<parameters.rust-min-version>>
            docker build --build-arg MIN_RUST_VERSION=<<parameters.rust-min-version>> -t ${REPO}/test:${TAG} --target test .
            docker run --rm ${REPO}/test:${TAG}

  publish_rust_env:
    parameters:
      rust-min-version:
        default: "1.56"
        type: string
    steps:
      - run:
          name: Publish for minimum version <<parameters.rust-min-version>>
          command: |
            REPO=jerusdp/ci-rust
            TAG=<<parameters.rust-min-version>>
            INPUT_RELEASE_VERSION=0.1.0
            docker build --build-arg MIN_RUST_VERSION=<<parameters.rust-min-version>> -t ${REPO}:${TAG} --target final .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push ${REPO}:${TAG}

  publish_base_cmd:
    steps:
      - run:
          name: Publish for minimum version base
          command: |
            REPO=jerusdp/ci-rust
            INPUT_RELEASE_VERSION=0.1.0
            docker build -t ${REPO}:base --target final .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push ${REPO}:base

  gpg-key:
    steps:
      - run:
          name: import GPG key
          command: |
            echo -e $BOT_GPG_KEY \
              | base64 --decode --ignore-garbage \
              | gpg --batch --allow-secret-key-import --import 
            gpg --fingerprint
            echo $BOT_TRUST | gpg --import-ownertrust
            gpg --fingerprint

  git-config:
    steps:
      - run:
          name: Configure git for user and signing
          command: |
            git config --global user.email "$BOT_USER_EMAIL"
            git config --global user.name "$BOT_USER_NAME"
            git config --global gpg.program gpg
            git config --global user.signingkey "$BOT_SIGN_KEY"
            git config --global commit.gpgsign true

jobs:
  test:
    parameters:
      min-rust-version:
        type: string
    executor: ubuntu
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: default
      - make-test:
          rust-min-version: << parameters.min-rust-version >>

  publish_rustcs:
    parameters:
      min-rust-version:
        type: string
    executor: ubuntu
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - publish_rust_env:
          rust-min-version: << parameters.min-rust-version >>

  publish_base:
    executor: ubuntu
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - publish_base_cmd

  pr-changelog-update:
    executor: ubuntu
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - SHA256:OkxsH8Z6Iim6WDJBaII9eTT9aaO1f3eDc6IpsgYYPVg
      - run:
          name: Remove original SSH key from agent
          command: |
            ssh-add -l
            ssh-add -d ~/.ssh/id_rsa.pub
            ssh-add -l
      - gpg-key
      - git-config
      - run:
          name: Install pcu
          command: |
            wget https://github.com/jerus-org/pcu/releases/download/v0.1.2/pcu
            chmod +x pcu
      - run:
          name: Update changelog
          command: |
            ./pcu -vv

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  check_last_commit:
    when:
      and:
        - not:
            equal: [scheduled_pipeline, << pipeline.trigger_source >>]
        - not: << pipeline.parameters.success-flag >>
        - not: << pipeline.parameters.validation-flag >>

    jobs:
      - toolkit/choose_pipeline:
          name: choose pipeline based on committer
          context: bot-check

  validation:
    when:
      and:
        - not:
            equal: [scheduled_pipeline, << pipeline.trigger_source >>]
        - not: << pipeline.parameters.success-flag >>
        - << pipeline.parameters.validation-flag >>
    jobs:
      - test:
          filters:
            branches:
              ignore: main
          matrix: &matrix
            parameters:
              min-rust-version:
                [
                  "1.33",
                  "1.61",
                  "1.65",
                  "1.67",
                  "1.71",
                  "1.72",
                  "1.73",
                  "1.74",
                  "1.75",
                  "1.76",
                ]

      - toolkit/update_changelog:
          requires:
            - test
          context:
            - release

  on_success:
    when:
      and:
        - not:
            equal: [scheduled_pipeline, << pipeline.trigger_source >>]
        - << pipeline.parameters.success-flag >>
        - not: << pipeline.parameters.validation-flag >>

    jobs:
      - toolkit/end_success

  release:
    when:
      and:
        - equal: [scheduled_pipeline, << pipeline.trigger_source >>]
        - equal: ["release check", << pipeline.schedule.name >>]
        - not: << pipeline.parameters.success-flag >>
        - not: << pipeline.parameters.validation-flag >>
    jobs:
      - toolkit/make_release:
          context:
            - release
          ssh_fingerprint: << pipeline.parameters.fingerprint >>
          min_rust_version: << pipeline.parameters.min-rust-version >>
